title RockenRollem



class CharacterContainer {
    ~ state
}

class CharacterRaceClassContainer {
  ~state
  - props
}



class CharacterStatsContainer {
  ~state
  - props
}

class DiceRoller {
  ~ state
}

class CharacterSheet {
  -props
}

class CharacterEquipmentContainer {
  ~state
  - props
}

class CharacterStoryContainer {
  ~state
  - props
}

class CharacterRace {
  - props
}

class CharacterClass {
  - props
}

class CharacterStats {
  - props
}

class CharacterGear {
  - props
}

class CharacterWeapons {
  - props
}

class Identity {
  - props
}

class Attributes {
  - props
}

class Proficiencies {
  - props
}

class Stats {
  - props
}

class Equipment {
  - props
}

class Background {
  - props
}

class Traits {
  - props
}



CharacterContainer *-- CharacterRaceClassContainer

CharacterContainer o---- CharacterSheet
CharacterSheet *-- Identity
CharacterSheet *-- Attributes
CharacterSheet *-- Proficiencies
CharacterSheet *-- Stats
CharacterSheet *-- Equipment
CharacterSheet *-- Background
CharacterSheet *-- Traits
CharacterContainer *-- CharacterStatsContainer
CharacterContainer *-- CharacterEquipmentContainer
CharacterContainer *-- CharacterStoryContainer
CharacterRaceClassContainer *-- CharacterRace
CharacterRaceClassContainer *-- CharacterClass
CharacterStatsContainer *-- CharacterStats
CharacterStatsContainer *-- DiceRoller
CharacterEquipmentContainer *-- CharacterGear
CharacterEquipmentContainer *-- CharacterWeapons
CharacterStoryContainer *-- CharacterStory

@enduml

# Generator Components and Containers
1. Home
2. RaceClass


# Components for character CharacterSheet
- Identity
- Attributes
- Proficiencies
- Stats
- Equipment
- Background
- Traits
